"""initial migration

Revision ID: 5b62805d7014
Revises: 
Create Date: 2026-02-05 13:29:14.596246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5b62805d7014'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_embeddings',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('embedding_version', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id')
    )
    op.create_index(op.f('ix_skill_embeddings_skill_id'), 'skill_embeddings', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_embeddings_updated_at'), 'skill_embeddings', ['updated_at'], unique=False)
    op.drop_index('idx_emp_skills_deleted_at', table_name='employee_skills')
    op.create_index(op.f('ix_employee_skills_deleted_at'), 'employee_skills', ['deleted_at'], unique=False)
    op.drop_index('idx_employees_deleted_at', table_name='employees')
    op.drop_index('idx_employees_email', table_name='employees')
    op.create_index(op.f('ix_employees_deleted_at'), 'employees', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.drop_index('uq_subcategories_category_name', table_name='skill_subcategories')
    op.drop_index('uq_skills_subcategory_name', table_name='skills')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_skills_subcategory_name', 'skills', ['subcategory_id', sa.text('lower(TRIM(BOTH FROM skill_name))')], unique=True)
    op.create_index('uq_subcategories_category_name', 'skill_subcategories', ['category_id', sa.text('lower(TRIM(BOTH FROM subcategory_name))')], unique=True)
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_deleted_at'), table_name='employees')
    op.create_index('idx_employees_email', 'employees', ['email'], unique=False)
    op.create_index('idx_employees_deleted_at', 'employees', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_employee_skills_deleted_at'), table_name='employee_skills')
    op.create_index('idx_emp_skills_deleted_at', 'employee_skills', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_skill_embeddings_updated_at'), table_name='skill_embeddings')
    op.drop_index(op.f('ix_skill_embeddings_skill_id'), table_name='skill_embeddings')
    op.drop_table('skill_embeddings')
    # ### end Alembic commands ###
